- name: Install the base system
  hosts: all
  tags: bootstrap
  environment: "{{ global_proxy_env }}"
  roles:
    - role: custom_repos
    # These roles pull partitioning and base_packages
    - role: bootloader
      tags: [bootloader]
    - role: configure
  post_tasks:
   - name: Reboot into the system
     tags: reboot
     reboot:

- name: Configure the installed system
  hosts: all
  tags: mainconfig
  environment: "{{ global_proxy_env }}"
  roles:
    # The hostname is set once during bootstrap and once here. The idea is to
    # set it as early as possible, but if bootstrap is skipped (i.e.
    # provisioning with Vagrant) we do it again here.
    - role: hostname
      vars:
        root: ""
    - role: custom_repos
    - role: users
    - role: locale
    - role: proxy
    - role: vboxguest
      tags: [vboxguest]
    - role: xfce_user_customizations
      tags: [xfce]
    - role: yay_user_customizations
      tags: [yay]
    - role: ttf_fonts
      tags: [ttf_fonts]
    - role: utils
      tags: [utils]
    - role: xutils
      tags: [xutils]
  post_tasks:
    - reboot:
      tags: reboot
