# A list of non-GUI packages to install. Both AUR and regular packages can be
# supplied here.
utils_packages:
  - ntfs-3g
  - p7zip
  - rsync
  - hexer
  - net-tools
  - iotop
  - pulseaudio
  - pulseaudio-alsa
