- name: Copy xfce's configuration for DarkBlue
  become: yes
  become_user: "{{ item }}"
  copy:
    src: darkblue/xfce4/
    dest: "{{ users_created | user_home(item) }}/.config/xfce4"
    mode: "0644"
  loop: "{{ users_names }}"
  when: item_theme.default | default(False, True) == True
  notify: Fix monitor name in XFCE settings
  register: _darkblue
  changed_when: _darkblue.changed or (run_handlers | default(false))
