- name: Copy xfce's configuration for Dracula
  become: yes
  become_user: "{{ item }}"
  copy:
    src: dracula/xfce4/
    dest: "{{ users_created | user_home(item) }}/.config/xfce4"
    mode: "0644"
  loop: "{{ users_names }}"
  when: item_theme.default | default(False, True) == True
  notify: Fix monitor name in XFCE settings
