FROM docker.io/debian:12

ENV DEBIAN_FRONTEND=noninteractive \
    DBUS_SYSTEM_BUS_ADDRESS=unix:path=/run/dbus/system_bus_socket \
    APT_INSTALL="apt-get install --no-install-recommends -o 'dpkg::options::=--force-confold' -o 'dpkg::options::=--force-confdef' -y" \
    APT_BUILDDEP="apt-get build-dep --no-install-recommends -o 'dpkg::options::=--force-confold' -o 'dpkg::options::=--force-confdef' -y" \
    PKGPROXY=/usr/local/bin/pkgproxy \
    SRC=/src \
    ARCH_ANSIBLE_LIBVIRT_USER_SESSION=1 \
    ARCH_ANSIBLE_HEADLESS=1 \
    CI_UID=1000 \
    CI_GID=1000 \
    CI_USER=ci
ENV PACKER_CACHE_DIR=/home/$CI_USER/.cache/packer

RUN \
    : "Add Debian backports" && \
        echo 'deb http://deb.debian.org/debian bookworm-backports main' > /etc/apt/sources.list.d/backports.list && \
        apt-get update && \
    : "Add Debian fast track repo" && \
        $APT_INSTALL fasttrack-archive-keyring && \
        echo 'deb http://fasttrack.debian.net/debian-fasttrack/ bookworm-fasttrack         main contrib' >  /etc/apt/sources.list.d/fasttrack.list && \
        echo 'deb http://fasttrack.debian.net/debian-fasttrack/ bookworm-backports-staging main contrib' >> /etc/apt/sources.list.d/fasttrack.list && \
        apt-get update && \
    : "Install curl" && \
        $APT_INSTALL --install-recommends curl && \
    : "Add HashiCorp repo" && \
        curl -Lo /etc/apt/trusted.gpg.d/hashicorp.asc https://apt.releases.hashicorp.com/gpg && \
        echo "deb https://apt.releases.hashicorp.com bookworm main" > /etc/apt/sources.list.d/hashicorp.list && \
        apt-get update && \
    : "Install tools and additional packages" && \
        $APT_INSTALL virtualbox vagrant libvirt-daemon-system dnsmasq packer qemu-system-x86 qemu-utils tini && \
    : "Prepare for vagrant-libvirt" && \
        sed -i -E 's/^(Types:\s*.*)/\1 deb-src/' /etc/apt/sources.list.d/debian.sources && \
        apt-get update && \
        $APT_BUILDDEP vagrant ruby-libvirt && \
        $APT_INSTALL vagrant libvirt-daemon-system ebtables libguestfs-tools libxslt-dev libxml2-dev zlib1g-dev ruby-dev && \
    : "Install pkgproxy" && \
        curl -L 'https://github.com/binary-manu/pkgproxy/releases/download/v2.0.1/pkgproxy' > "$PKGPROXY" && \
        chmod a+x "$PKGPROXY" && \
    : "Ensure qemu's bridge helper can be run with appropriate privileges" && \
        mkdir -p /etc/qemu/ && echo "allow virbr0" > /etc/qemu/bridge.conf && \
        chmod u+s /usr/lib/qemu/qemu-bridge-helper && \
    : "Install GitHub runner agent" && \
        curl -o /tmp/ghrunner.tar.gz -L https://github.com/actions/runner/releases/download/v2.319.1/actions-runner-linux-x64-2.319.1.tar.gz && \
        mkdir -p /tmp/gh && tar -xzf /tmp/ghrunner.tar.gz -C /tmp/gh && \
        /tmp/gh/bin/installdependencies.sh && \
    : "Create ci user" && \
        groupadd -g $CI_GID $CI_USER && \
        useradd -d /home/$CI_USER -m -s /bin/bash -c "CI agent user" -u $CI_UID -g $CI_GID $CI_USER && \
    : "Cleanup" && \
        apt-get clean && apt-get autoremove --purge && \
        rm -rf /var/lib/apt/lists/*



USER ci:ci

RUN \
    : "Install GH Agent to ~" && \
        mkdir -p ~/gh && \
        tar -xzf /tmp/ghrunner.tar.gz -C ~/gh && \
    : "Install vagrant-libvirt" && \
        vagrant plugin install vagrant-libvirt && \
    : "Install Packer plugins" && \
        packer plugins install github.com/hashicorp/ansible && \
        packer plugins install github.com/hashicorp/virtualbox && \
        packer plugins install github.com/hashicorp/qemu

VOLUME /home/$CI_USER

COPY ./entry.sh /entry.sh
ENTRYPOINT ["/usr/bin/tini", "--", "/entry.sh"]
CMD ["/home/ci/gh/run.sh"]

# vi: set nowrap :
